windows: retry rcedit multiple times

diff --git a/windows-msys/make_dist_dir.sh.in b/windows-msys/make_dist_dir.sh.in
--- a/windows-msys/make_dist_dir.sh.in
+++ b/windows-msys/make_dist_dir.sh.in
@@ -54,6 +54,28 @@ dist_plugins_dir=$dist_dir/plugins
 install_data="install -m 644"
 glib_schemas_dir_suffix=share/glib-2.0/schemas
 
+function fail {
+  echo $1 >&2
+  exit 1
+}
+
+function retry {
+  local n=1
+  local max=5
+  local delay=1
+  while true; do
+    "$@" && break || {
+      if [[ $n -lt $max ]]; then
+        ((n++))
+        echo "Command failed. Attempt $n/$max:"
+        sleep $delay;
+      else
+        fail "The command has failed after $n attempts."
+      fi
+    }
+  done
+}
+
 main () {
   # make the dirs
   rm -rf $private_dir
@@ -233,8 +255,8 @@ EOL
   "$dist_bindir/cv2pdb/cv2pdb64.exe" "$zrythm_exe" "$dist_bindir/zrythm_debug_vs.exe"
   rm -rf "$dist_bindir/cv2pdb"
 
-  # rcedited version of original (try twice because sometimes it fails)
-  $rcedit_x64_exe "$zrythm_exe" --set-icon  "$dist_dir/zrythm.ico" || $rcedit_x64_exe "$zrythm_exe" --set-icon  "$dist_dir/zrythm.ico"
+  # rcedited version of original (try a few times because sometimes it fails)
+  retry $rcedit_x64_exe "$zrythm_exe" --set-icon  "$dist_dir/zrythm.ico"
   "$zrythm_exe" --version
 
   # ******************************
